# Netlify設定ファイル

[[headers]]
  for = "/*"
  [headers.values]
    # セキュリティヘッダー
    Permissions-Policy = "camera=(*), microphone=(), geolocation=()"
    
    # HTTPSを強制
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # XSSプロテクション
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # リファラーポリシー
    Referrer-Policy = "no-referrer-when-downgrade"

# リダイレクト設定
[[redirects]]
  from = "http://mujura.netlify.app/*"
  to = "https://mujura.netlify.app/:splat"
  status = 301
  force = true