# Netlify設定ファイル

# JavaScriptファイルのMIMEタイプを明示的に設定
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

# CSSファイルのMIMEタイプを明示的に設定
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*"
  [headers.values]
    # HTTPSを強制
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # XSSプロテクション
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # リファラーポリシー
    Referrer-Policy = "no-referrer-when-downgrade"

# リダイレクト設定
[[redirects]]
  from = "http://mujura.netlify.app/*"
  to = "https://mujura.netlify.app/:splat"
  status = 301
  force = true